### ISSUE TITLE
유저 등록 테스트 

### ISSUE THREAD

**Issue by jhva** [wanted-preonboarding-team-m/01_SocialIntegrateFreed#26]
## 📝 Description

전반적인 유저 관련 테스트 

## ☑️ TODO

- [x] 사용자 등록 테스트 
- [ ] 인증 코드 테스트 
- [ ] 재발급 코드 테스트 
- [ ] 로그인 테스트 (feat :Security)
