### ISSUE TITLE
유저 등록 구현

### ISSUE THREAD

**Issue by jhva** [wanted-preonboarding-team-m/01_SocialIntegrateFreed#6]
## 📝 Description

유저 가입
- `UserRepository` 기본적인 Create에 대한 테스트  
- `UserService` 기본적인 Create에 대한 Service 테스트를 한다. 
   1. `Request`,`Response` Dto 생성 
- `UserController`  기본적인 Create에 대한 Controller 테스트 및 실행 결과 
-  `JWT` 토큰 생성
- `Spring-Security` 를 통해 인가/인증 설정 

## ☑️ TODO

- [x] UserRepository Create 테스트 
- [x] UserService클래스 생성 및 UserService Create 테스트 클래스 생성 ,Dto 클래스 생성 
- [x] UserController클래스 생성 및 UserController Create 테스트 클래스 생성 
- [x] JWT 생성 및 테스트 구현 
- [x] Spring-Security 전역 설정
